import React, { useState, useEffect } from "react";
import {
  Code,
  Sliders,
  Sparkles,
  Copy,
  Check,
  BookOpen,
  Info,
  Flame,
  Wand2,
  RefreshCw,
  Cpu,
  Layers,
  ChevronRight
} from "lucide-react";
import GameCanvas from "./components/GameCanvas";
import { initialScripts } from "./initialScripts";
import { GameVariables, CSharpScript } from "./types";

export default function App() {
  // Active component selected in inspector / script tabs
  const [activeTab, setActiveTab] = useState<string>("PlayerController");
  
  // Custom scripts generated by AI
  const [scripts, setScripts] = useState<{ [key: string]: CSharpScript }>(initialScripts);
  
  // Game Variables (binds directly to physics & inspector)
  const [variables, setVariables] = useState<GameVariables>({
    doubleJumpEnabled: true,
    jumpForce: 12,
    gravityScale: 2.2,
    dashEnabled: true,
    maxSpeed: 5,
    collectibleValue: 10,
    particlesDensity: 1,
    bounceForce: 15,
    playerColor: "#ffffff",
    cameraShakeEnabled: true,
    activeScriptComponent: "PlayerController",
  });

  // AI Prompt inputs
  const [promptInput, setPromptInput] = useState<string>("");
  const [isGenerating, setIsGenerating] = useState<boolean>(false);
  const [aiError, setAiError] = useState<string | null>(null);
  
  // Copy state
  const [copied, setCopied] = useState<boolean>(false);

  // Sync variables when switching component tabs to represent the active script settings
  useEffect(() => {
    const activeScript = scripts[activeTab];
    if (activeScript && activeScript.gameVariables) {
      setVariables((prev) => ({
        ...prev,
        ...activeScript.gameVariables,
        activeScriptComponent: activeTab,
      }));
    }
  }, [activeTab, scripts]);

  // Handle value changes in Unity Inspector
  const handleInspectorChange = (key: keyof GameVariables, value: any) => {
    setVariables((prev) => ({
      ...prev,
      [key]: value,
    }));
  };

  // Preset theme color selections (Hollow Knight references)
  const colorPresets = [
    { name: "Чистый Гвоздь", color: "#ffffff" },
    { name: "Бездна", color: "#a855f7" },
    { name: "Зеленая тропа", color: "#22c55e" },
    { name: "Город Слез", color: "#06b6d4" },
    { name: "Кошмар Гримма", color: "#ef4444" },
  ];

  // Copy code to clipboard
  const handleCopyCode = () => {
    const code = scripts[activeTab]?.code || "";
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // AI Script Generator call
  const generateCustomScript = async () => {
    if (!promptInput.trim()) return;
    setIsGenerating(true);
    setAiError(null);

    try {
      const response = await fetch("/api/generate-unity-script", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          prompt: promptInput,
          currentVariables: variables,
          activeComponent: activeTab,
        }),
      });

      if (!response.ok) {
        throw new Error("Не удалось подключиться к серверу ИИ. Попробуйте еще раз.");
      }

      const data = await response.json();
      
      if (data.error) {
        throw new Error(data.error);
      }

      // Format custom component name
      const componentName = data.gameVariables?.activeScriptComponent || "CustomController";
      
      // Save new script
      setScripts((prev) => ({
        ...prev,
        [componentName]: {
          code: data.code,
          guide: data.guide,
          summary: data.summary,
          gameVariables: data.gameVariables,
        },
      }));

      // Switch to generated tab
      setActiveTab(componentName);

      // Apply gameplay variables if any
      if (data.gameVariables) {
        setVariables((prev) => ({
          ...prev,
          ...data.gameVariables,
          activeScriptComponent: componentName,
        }));
      }

      setPromptInput("");
    } catch (err: any) {
      console.error(err);
      setAiError(err.message || "Произошла непредвиденная ошибка во время сборки кода.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#0c1120] text-slate-100 flex flex-col font-sans antialiased selection:bg-teal-500/30 selection:text-teal-200 relative overflow-hidden">
      
      {/* Atmospheric Background Elements */}
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,#1e293b_0%,transparent_50%)] opacity-40 pointer-events-none"></div>
      <div className="absolute bottom-[-100px] left-[-100px] w-[400px] h-[400px] bg-teal-500/10 rounded-full blur-[120px] pointer-events-none"></div>
      <div className="absolute top-1/4 right-[-50px] w-[300px] h-[300px] bg-indigo-500/10 rounded-full blur-[100px] pointer-events-none"></div>

      {/* Header Panel */}
      <header className="border-b border-white/10 bg-slate-950/60 backdrop-blur-md px-6 py-4 flex flex-col sm:flex-row items-center justify-between gap-4 sticky top-0 z-50 relative">
        <div className="flex items-center space-x-3">
          <div className="p-2.5 rounded-xl bg-gradient-to-tr from-teal-500 to-indigo-600 text-white shadow-lg shadow-teal-950/40">
            <Cpu className="w-5 h-5" />
          </div>
          <div>
            <h1 className="text-md sm:text-lg font-bold tracking-tight text-white flex items-center gap-2">
              Unity 2D & C# Code Companion
              <span className="text-[10px] bg-teal-500/10 border border-teal-500/20 text-teal-300 font-mono px-2 py-0.5 rounded-full uppercase">
                v1.2
              </span>
            </h1>
            <p className="text-xs text-slate-400">
              Полноценная игра и симулятор Unity-скриптов для создания атмосферных платформеров.
            </p>
          </div>
        </div>

        <div className="flex items-center space-x-2 text-[11px] font-mono bg-slate-900/60 border border-white/10 p-1.5 px-3 rounded-lg text-slate-300">
          <span className="w-2 h-2 rounded-full bg-teal-400 shadow-[0_0_10px_#2dd4bf] animate-pulse mr-1"></span>
          <span>C# Движок Готов</span>
        </div>
      </header>

      {/* Main Interactive Layout */}
      <main className="flex-1 max-w-7xl w-full mx-auto p-4 sm:p-6 lg:p-8 grid grid-cols-1 lg:grid-cols-12 gap-8 items-start relative z-10">
        
        {/* LEFT COLUMN: Playable Game & Unity Inspector (5 cols) */}
        <section className="lg:col-span-5 flex flex-col space-y-6">
          <div className="flex items-center justify-between px-1">
            <h2 className="text-sm font-semibold text-slate-200 flex items-center gap-1.5 uppercase tracking-wider">
              <Layers className="w-4 h-4 text-teal-400" />
              Интерактивное Веб-Демо
            </h2>
            <span className="text-xs text-slate-400 font-mono">HTML5 Canvas Physics</span>
          </div>

          <GameCanvas
            variables={variables}
            onCollect={(amt) => {}}
            onHeightReached={(ht) => {}}
          />

          {/* SIMULATED UNITY INSPECTOR */}
          <div className="bg-slate-950/50 backdrop-blur-xl border border-white/10 rounded-2xl p-5 shadow-2xl">
            <div className="flex items-center justify-between border-b border-white/5 pb-3 mb-4">
              <div className="flex items-center space-x-2">
                <Sliders className="w-4 h-4 text-teal-400" />
                <h3 className="text-sm font-bold text-slate-200">Unity Inspector</h3>
              </div>
              <span className="text-[10px] font-mono text-slate-500 uppercase">Selected: {activeTab}</span>
            </div>

            <div className="space-y-4">
              {/* Variable inputs grouped */}
              <div className="bg-slate-950/40 rounded-xl p-3 border border-white/5 space-y-3">
                <span className="text-[10px] text-slate-400 font-mono font-bold tracking-wider uppercase block">Физика Рыцаря</span>
                
                {/* Max Speed */}
                <div className="flex items-center justify-between">
                  <label className="text-xs text-slate-300 font-mono">Move Speed (moveSpeed)</label>
                  <div className="flex items-center space-x-3">
                    <input
                      type="range"
                      min="3"
                      max="10"
                      step="0.5"
                      value={variables.maxSpeed}
                      onChange={(e) => handleInspectorChange("maxSpeed", parseFloat(e.target.value))}
                      className="w-24 h-1 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-teal-400"
                    />
                    <span className="text-xs font-mono text-teal-400 w-8 text-right">{variables.maxSpeed}f</span>
                  </div>
                </div>

                {/* Jump Force */}
                <div className="flex items-center justify-between">
                  <label className="text-xs text-slate-300 font-mono">Jump Force (jumpForce)</label>
                  <div className="flex items-center space-x-3">
                    <input
                      type="range"
                      min="8"
                      max="16"
                      step="0.5"
                      value={variables.jumpForce}
                      onChange={(e) => handleInspectorChange("jumpForce", parseFloat(e.target.value))}
                      className="w-24 h-1 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-teal-400"
                    />
                    <span className="text-xs font-mono text-teal-400 w-8 text-right">{variables.jumpForce}f</span>
                  </div>
                </div>

                {/* Gravity Scale */}
                <div className="flex items-center justify-between">
                  <label className="text-xs text-slate-300 font-mono">Gravity Scale (gravity)</label>
                  <div className="flex items-center space-x-3">
                    <input
                      type="range"
                      min="1"
                      max="4"
                      step="0.1"
                      value={variables.gravityScale}
                      onChange={(e) => handleInspectorChange("gravityScale", parseFloat(e.target.value))}
                      className="w-24 h-1 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-teal-400"
                    />
                    <span className="text-xs font-mono text-teal-400 w-8 text-right">{variables.gravityScale}f</span>
                  </div>
                </div>
              </div>

              {/* Boolean toggles */}
              <div className="grid grid-cols-2 gap-3">
                <label className="flex items-center justify-between p-3 rounded-xl bg-slate-950/40 border border-white/5 cursor-pointer hover:bg-slate-900/40 transition-colors">
                  <span className="text-xs text-slate-300 font-mono">Double Jump</span>
                  <input
                    type="checkbox"
                    checked={variables.doubleJumpEnabled}
                    onChange={(e) => handleInspectorChange("doubleJumpEnabled", e.target.checked)}
                    className="w-4 h-4 text-teal-400 bg-slate-850 rounded border-slate-700 focus:ring-teal-400 cursor-pointer accent-teal-400"
                  />
                </label>

                <label className="flex items-center justify-between p-3 rounded-xl bg-slate-950/40 border border-white/5 cursor-pointer hover:bg-slate-900/40 transition-colors">
                  <span className="text-xs text-slate-300 font-mono">Dash Enabled</span>
                  <input
                    type="checkbox"
                    checked={variables.dashEnabled}
                    onChange={(e) => handleInspectorChange("dashEnabled", e.target.checked)}
                    className="w-4 h-4 text-teal-400 bg-slate-850 rounded border-slate-700 focus:ring-teal-400 cursor-pointer accent-teal-400"
                  />
                </label>
              </div>

              {/* Advanced Mechanics parameters */}
              <div className="bg-slate-950/40 rounded-xl p-3 border border-white/5 space-y-3">
                <span className="text-[10px] text-slate-400 font-mono font-bold tracking-wider uppercase block">Вторичные свойства</span>
                
                {/* Spring Bounce */}
                <div className="flex items-center justify-between">
                  <label className="text-xs text-slate-300 font-mono">Spring Force</label>
                  <div className="flex items-center space-x-3">
                    <input
                      type="range"
                      min="10"
                      max="20"
                      step="0.5"
                      value={variables.bounceForce}
                      onChange={(e) => handleInspectorChange("bounceForce", parseFloat(e.target.value))}
                      className="w-24 h-1 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-teal-400"
                    />
                    <span className="text-xs font-mono text-teal-400 w-8 text-right">{variables.bounceForce}f</span>
                  </div>
                </div>

                {/* Particle Multiplier */}
                <div className="flex items-center justify-between">
                  <label className="text-xs text-slate-300 font-mono">Particles multiplier</label>
                  <div className="flex items-center space-x-3">
                    <input
                      type="range"
                      min="0.5"
                      max="3"
                      step="0.5"
                      value={variables.particlesDensity}
                      onChange={(e) => handleInspectorChange("particlesDensity", parseFloat(e.target.value))}
                      className="w-24 h-1 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-teal-400"
                    />
                    <span className="text-xs font-mono text-teal-400 w-8 text-right">{variables.particlesDensity}x</span>
                  </div>
                </div>
              </div>

              {/* Player Color Presets */}
              <div className="bg-slate-950/40 rounded-xl p-3 border border-white/5">
                <span className="text-[10px] text-slate-400 font-mono font-bold tracking-wider uppercase block mb-2">Цвет свечения Душ</span>
                <div className="flex flex-wrap gap-2">
                  {colorPresets.map((pr) => (
                    <button
                      key={pr.name}
                      onClick={() => handleInspectorChange("playerColor", pr.color)}
                      className={`flex items-center space-x-1.5 px-2 py-1 rounded-lg text-[10px] border transition-all cursor-pointer ${
                        variables.playerColor === pr.color
                          ? "bg-teal-500/20 border-teal-500 text-teal-300 font-semibold"
                          : "bg-slate-900/40 border-white/10 text-slate-400 hover:border-slate-700"
                      }`}
                    >
                      <span
                        className="w-2 h-2 rounded-full shadow-inner"
                        style={{ backgroundColor: pr.color }}
                      />
                      <span>{pr.name}</span>
                    </button>
                  ))}
                </div>
              </div>

              {/* Camera shake */}
              <label className="flex items-center justify-between p-3 rounded-xl bg-slate-950/40 border border-white/5 cursor-pointer hover:bg-slate-900/40 transition-colors">
                <span className="text-xs text-slate-300 font-mono">Camera Shake (тряска)</span>
                <input
                  type="checkbox"
                  checked={variables.cameraShakeEnabled}
                  onChange={(e) => handleInspectorChange("cameraShakeEnabled", e.target.checked)}
                  className="w-4 h-4 text-teal-400 bg-slate-850 rounded border-slate-700 focus:ring-teal-400 cursor-pointer accent-teal-400"
                />
              </label>
            </div>
          </div>
        </section>

        {/* RIGHT COLUMN: Code tab view, AI generator, guides (7 cols) */}
        <section className="lg:col-span-7 flex flex-col space-y-6">
          
          {/* AI GENERATOR PROMPT */}
          <div className="bg-slate-950/50 backdrop-blur-xl border border-white/10 rounded-2xl p-5 shadow-2xl">
            <div className="flex items-center space-x-2 mb-3">
              <Wand2 className="w-4 h-4 text-teal-400 animate-pulse" />
              <h3 className="text-sm font-bold text-slate-200">🤖 AI Модификатор кода (Unity + C#)</h3>
            </div>
            
            <p className="text-xs text-slate-400 mb-4 leading-relaxed">
              Напишите словами, какую механику вы хотите внедрить в игру (например: <span className="text-teal-300 font-mono">"добавь тройной прыжок"</span>, <span className="text-teal-300 font-mono">"сделай прыжок от стены"</span> или <span className="text-teal-300 font-mono">"исчезающая платформа"</span>).
              Gemini сгенерирует готовый C#-код для Unity и мгновенно активирует механику в веб-демо слева!
            </p>

            <div className="flex flex-col sm:flex-row gap-3">
              <input
                type="text"
                placeholder="Добавить тройной прыжок, рывок вверх, скольжение..."
                value={promptInput}
                onChange={(e) => setPromptInput(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter" && !isGenerating) generateCustomScript();
                }}
                disabled={isGenerating}
                className="flex-1 bg-slate-950/80 border border-white/10 rounded-xl px-4 py-2.5 text-xs text-slate-200 placeholder-slate-500 focus:outline-none focus:border-teal-500 transition-colors disabled:opacity-50"
              />
              <button
                onClick={generateCustomScript}
                disabled={isGenerating || !promptInput.trim()}
                className="bg-gradient-to-r from-teal-500 to-indigo-600 hover:from-teal-400 hover:to-indigo-500 text-white px-5 py-2.5 rounded-xl text-xs font-semibold shadow-lg shadow-teal-950/30 flex items-center justify-center gap-2 transition-all disabled:opacity-50 disabled:pointer-events-none cursor-pointer"
              >
                {isGenerating ? (
                  <>
                    <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                    Компиляция...
                  </>
                ) : (
                  <>
                    <Sparkles className="w-3.5 h-3.5" />
                    Генерировать C#
                  </>
                )}
              </button>
            </div>

            {aiError && (
              <div className="mt-3 p-3 bg-red-500/10 border border-red-500/20 text-red-400 text-xs rounded-xl flex items-center gap-2 font-mono">
                <Info className="w-4 h-4 flex-shrink-0" />
                <span>{aiError}</span>
              </div>
            )}
          </div>

          {/* SCRIPT TABS VIEW */}
          <div className="bg-slate-950/50 backdrop-blur-xl border border-white/10 rounded-2xl p-5 shadow-2xl flex flex-col flex-1 min-h-[500px]">
            
            {/* Tabs bar */}
            <div className="flex flex-wrap gap-2 border-b border-white/5 pb-3 mb-4">
              {Object.keys(scripts).map((key) => (
                <button
                  key={key}
                  onClick={() => setActiveTab(key)}
                  className={`px-3 py-1.5 rounded-xl text-xs font-mono transition-all cursor-pointer ${
                    activeTab === key
                      ? "bg-teal-500/20 border border-teal-500/40 text-teal-300"
                      : "text-slate-400 hover:text-slate-200 bg-slate-950/20 border border-transparent hover:bg-slate-950/40"
                  }`}
                >
                  {key}.cs
                </button>
              ))}
            </div>

            {/* Script Details */}
            {scripts[activeTab] ? (
              <div className="flex flex-col flex-1 space-y-4">
                
                {/* Script Summary */}
                <div className="p-4 bg-slate-950/40 border border-white/5 rounded-xl flex items-start gap-3">
                  <div className="p-2 rounded-lg bg-teal-500/10 text-teal-400 mt-0.5">
                    <Info className="w-4 h-4" />
                  </div>
                  <div>
                    <h4 className="text-xs font-bold text-slate-200 mb-1 font-mono">Обзор Скрипта в Unity</h4>
                    <p className="text-xs text-slate-400 leading-relaxed">
                      {scripts[activeTab].summary}
                    </p>
                  </div>
                </div>

                {/* Sub-Tabs: Code & Guide */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 flex-1">
                  
                  {/* Left sub-column: C# Code Viewer */}
                  <div className="flex flex-col space-y-2">
                    <div className="flex items-center justify-between px-1">
                      <span className="text-[10px] text-slate-400 font-mono font-bold tracking-wider uppercase flex items-center gap-1.5">
                        <Code className="w-3.5 h-3.5 text-teal-400" />
                        Код C# Script
                      </span>
                      <button
                        onClick={handleCopyCode}
                        className="flex items-center gap-1.5 px-2.5 py-1 text-[10px] bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg border border-white/10 transition-all cursor-pointer"
                        title="Copy Script to Clipboard"
                      >
                        {copied ? (
                          <>
                            <Check className="w-3 h-3 text-emerald-400" />
                            <span className="text-emerald-400 font-semibold">Скопировано</span>
                          </>
                        ) : (
                          <>
                            <Copy className="w-3 h-3" />
                            <span>Копировать</span>
                          </>
                        )}
                      </button>
                    </div>

                    <div className="relative flex-1 min-h-[300px] bg-slate-950/80 rounded-xl border border-white/10 overflow-hidden flex flex-col">
                      {/* Window header */}
                      <div className="bg-slate-900/60 border-b border-white/5 px-4 py-2 flex items-center justify-between">
                        <div className="flex space-x-1.5">
                          <span className="w-2.5 h-2.5 rounded-full bg-red-500/60"></span>
                          <span className="w-2.5 h-2.5 rounded-full bg-yellow-500/60"></span>
                          <span className="w-2.5 h-2.5 rounded-full bg-green-500/60"></span>
                        </div>
                        <span className="text-[9px] text-slate-500 font-mono uppercase">MonoBehaviour Engine</span>
                      </div>
                      
                      {/* Real scrollable code pre */}
                      <pre className="flex-1 overflow-auto p-4 text-[11px] font-mono leading-relaxed text-slate-300 text-left select-text scrollbar-thin">
                        <code>{scripts[activeTab].code}</code>
                      </pre>
                    </div>
                  </div>

                  {/* Right sub-column: Unity Integration Guide */}
                  <div className="flex flex-col space-y-2">
                    <span className="text-[10px] text-slate-400 font-mono font-bold tracking-wider uppercase flex items-center gap-1.5 px-1">
                      <BookOpen className="w-3.5 h-3.5 text-teal-400" />
                      Инструкция настройки в Unity
                    </span>

                    <div className="relative flex-1 min-h-[300px] bg-slate-950/60 border border-white/10 rounded-xl p-4 overflow-y-auto text-left leading-relaxed text-slate-300 text-xs max-h-[400px]">
                      {/* Render custom styled markdown manual */}
                      <div className="space-y-3 prose prose-invert prose-xs text-xs">
                        {scripts[activeTab].guide.split("\n").map((line, idx) => {
                          if (line.startsWith("###")) {
                            return (
                              <h4 key={idx} className="text-xs font-bold text-teal-300 mt-4 border-b border-white/5 pb-1 flex items-center gap-1">
                                <ChevronRight className="w-3 h-3 text-teal-400" />
                                {line.replace("###", "").trim()}
                              </h4>
                            );
                          } else if (line.startsWith("-") || line.startsWith("*")) {
                            return (
                              <li key={idx} className="ml-4 list-disc text-slate-300 text-[11px] list-inside">
                                {line.replace(/^[-*]\s*/, "").trim()}
                              </li>
                            );
                          } else if (/^\d+\./.test(line)) {
                            return (
                              <div key={idx} className="font-bold text-slate-200 text-xs mt-3">
                                {line}
                              </div>
                            );
                          } else if (line.trim() === "") {
                            return <div key={idx} className="h-1" />;
                          } else {
                            return <p key={idx} className="text-slate-400 text-[11px]">{line}</p>;
                          }
                        })}
                      </div>
                    </div>
                  </div>
                </div>

              </div>
            ) : (
              <div className="flex-1 flex flex-col items-center justify-center text-center p-8">
                <Flame className="w-10 h-10 text-slate-600 animate-bounce mb-3" />
                <p className="text-xs text-slate-500">Пожалуйста, выберите существующий C# компонент.</p>
              </div>
            )}
          </div>
        </section>

      </main>

      {/* Footer */}
      <footer className="border-t border-white/10 bg-slate-950/60 py-6 text-center text-xs text-slate-500 font-mono mt-12 relative z-10">
        <p>© 2026 Hollow Jump Companion • Создано на React + Canvas + Google Gemini AI</p>
      </footer>
    </div>
  );
}
